language: java

sudo: false
install: true
addons:
  sonarcloud:
    organization: vova-oss
    token:
      secure: 49c132cdbc6de500ca08cdd51f0d7832cdf24263

jdk:
  - openjdk-21
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'

notifications:
  email:
    recipients:
      - ogyrcka@gmail.com
    on_success: always
    on_failure: always