language: java

sudo: false
install: true
addons:
  sonarcloud:
    organization: vova-oss

jdk:
  - openjdk-21
script:
  - mvn clean install sonar:sonar -Dsonar.projectKey=Vova-oss_YIVPRPO

#cache:
#  directories:
#    - '$HOME/.m2/repository'
#    - '$HOME/.sonar/cache'

notifications:
  email:
    recipients:
      - ogyrcka@gmail.com
    on_success: always
    on_failure: always