language: java

sudo: false
install: true
addons:
  sonarcloud:
    organization: vova-oss

jdk:
  - openjdk-21
script:
  - mvn clean install sonar:sonar -Dsonar.projectKey=Vova-oss_YIVPRPO

after_success:
  - mvn clean test jacoco:report coveralls:report

notifications:
  email:
    recipients:
      - ogyrcka@gmail.com
    on_success: never
    on_failure: always